module.exports = {
    auth: 'auth',
    user: 'user',
    recipe: 'recipe',
    recipe_category: 'recipe_category',
    recipe_comment: 'recipe_comment',
    recipe_rating: 'recipe_rating',
    recipe_id: 'recipe_id',
    version: '__v',
    followersCount: 'followersCount',
    followsForCount: 'followsForCount',
    followers: 'followers',
    followsFor: 'followsFor',
    password: 'password',
    createdAt: 'createdAt',
    updatedAt: 'updatedAt',
    id: 'id',
    likes_count: 'likes_count',
    likes: 'likes',
    notification: 'notification',
    notifications: 'notifications'
};
