const { csvFileNamesEnum } = require('./csvFileNames.enum');

module.exports = {
    PORT: process.env.PORT,
    FRONT_END_URL: process.env.FRONT_END_URL,
    MONGODB_URI: process.env.MONGODB_URI,
    JWT_SECRET_AUTH: process.env.JWT_SECRET_AUTH,
    JWT_SECRET_ACTION: process.env.JWT_SECRET_ACTION,
    JWT_AUTH_EXPIRES_IN: process.env.JWT_AUTH_EXPIRES_IN,
    JWT_ACTION_EXPIRES_IN: process.env.JWT_ACTION_EXPIRES_IN,
    APP_EMAIL: process.env.APP_EMAIL,
    APP_EMAIL_PASSWORD: process.env.APP_EMAIL_PASSWORD,
    EMAIL_SERVICE: process.env.EMAIL_SERVICE,
    S3_REGION: process.env.S3_REGION,
    S3_ACCESS_KEY: process.env.S3_ACCESS_KEY,
    S3_SECRET_KEY: process.env.S3_SECRET_KEY,
    S3_BUCKET_NAME: process.env.S3_BUCKET_NAME,
    CSV_DOWNLOADS_URL: process.env.CSV_DOWNLOADS_URL,
    NEAR_USER_RADIUS_KM: process.env.NEAR_USER_RADIUS_KM,
    DEFAULT_USER_IMAGE: process.env.DEFAULT_USER_IMAGE,
    RADIAN_IN_KM: 6378.1,
    csvFileNamesEnum: require('./csvFileNames.enum'),
    regExpEnum: require('./regex.enum'),
    statusCodesEnum: require('./statusCodes.enum'),
    dbTablesEnum: require('./dbTables.enum'),
    recipesCategoriesEnum: require('./recipeCategories.enum'),
    emailsEnum: require('./emails.enum'),
    recipeSchemaFieldsEnum: require('./recipeSchemaFields.enum'),
    socketEventsEnum: require('./socketEvents.enum'),
    notificationTypesEnum: require('./notificationTypes.enum'),
    tokensTypesEnum: require('./tokensTypes.enum'),
    photoTypesEnum: require('./photoTypes.enum'),
};
